FROM maven:3.6.3-adoptopenjdk-8

RUN apt-get update \
    && apt-get install -y gpg \
    && apt-get clean

USER jenkins

#set locale

ENV LANG nl_NL.UTF-8
ENV LANGUAGE nl_NL:nl
ENV LC_ALL nl_NL.UTF-8  
